# Use the official Python image as a parent image
FROM python:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Define the command to start the MQTT Subscriber application
CMD ["python", "mqtt_subscriber.py"]
